web:
    image: nginx
    container_name: web_server
    ports:
        - "80:80"
    volumes:
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./code:/code
    links:
        - php

php:
    build: .
    container_name: php
    volumes:
        - ./code:/code
    links:
        - db

db:
    image: mariadb
    container_name: database
    restart: always
    ports:
        - "3306:3306"
    volumes:
        - ./mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
