web:
    image: nginx
    container_name: web_server
    ports:
        - 8080:80
    volumes:
        - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        - ./public:/public
    links:
        - php

php:
    build: .
    container_name: php
    volumes:
        - ./public:/public
    links:
        - db

db:
    image: mariadb
    container_name: database
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
